### ISSUE TITLE
installation issues on windows

### ISSUE THREAD

**Issue by plasmax** [jlowin/fastmcp#36]
Love this idea, trying to install/get it working on windows, so if anyone else has please let me know your steps.

Other mcp servers are working with this caude_desktop_config.json:

```json
{
  "mcpServers": {
    "filesystem": {
      "command": "node",
      "args": [
        "C:\\Users\\Max\\AppData\\Roaming\\npm\\node_modules\\@modelcontextprotocol\\server-filesystem\\dist\\index.js", 
        "E:\\Repositories\\sandbox"
      ]
    },
    "git": {
      "command": "python",
      "args": ["-m", "mcp_server_git", "--repository", "E:\\Repositories\\bloom\\"]
    },
    "mcpserver": {
      "command": "uv",
      "args": [
        "--directory",
        "E:\\Repositories\\sandbox\\mcpserver",
        "run",
        "mcpserver"
      ]
    },  
    "Demo": {
      "command": "uv",
      "args": [
        "run",
        "--with",
        "fastmcp",
        "fastmcp",
        "run",
        "E:\\Repositories\\sandbox\\demo.py"
      ]
    }
  }
}
```

I've tried (in windsurf cmd prompt):
```
E:\Repositories\sandbox>uv pip install fastmcp      
Audited 1 package in 13ms

E:\Repositories\sandbox>fastmcp install demo.py
'fastmcp' is not recognized as an internal or external command,
operable program or batch file.

E:\Repositories\sandbox>C:\Users\Max\AppData\Roaming\Python\Python312\Scripts\fastmcp.exe install demo.py
[12/02/24 09:17:43] 
INFO     Added server 'Demo' to Claude config            claude.py:108                    
INFO     Successfully installed Demo in Claude app       cli.py:402
```

So the installation went well, but when restarting Claude Desktop, it failed to recognise fastmcp. The cmd terminal launches in the background, but then closes, suggesting an error somewhere, but there's no traceback.

Not sure if we can run servers externally? I tried this and it just sits there, and Claude doesn't recognise it even after a restart:
```
E:\Repositories\sandbox>C:\Users\Max\AppData\Roaming\Python\Python312\Scripts\fastmcp.exe run demo.py    
```

then I tried this:
```
E:\Repositories\sandbox>C:\Users\Max\AppData\Roaming\Python\Python312\Scripts\fastmcp.exe run E:\Repositories\sandbox\demo.py
File not found: E:\Repositories\sandbox\E
```

Which suggests that's the root of the problem - maybe fastmcp is not handling windows paths very well at the moment? How can I get more verbose output?

I've tried with and without venv, pip installing directly, using uv, etc...

I've also tried calling fastmcp directly from claude's config:

```json
    "Demo": {
      "command": "C:\\Users\\Max\\AppData\\Roaming\\Python\\Python312\\Scripts\\fastmcp.exe",
      "args": [
        "run",
        "E:\\Repositories\\sandbox\\demo.py"
      ]
    }
```

So far no luck.

**Comment by jlowin** [comment]
Thanks for the report - definitely odd, I will look into this. If you have any other detail / logs please share them, and I can try to add more verbose output in places that will help.

**Comment by justjoehere** [comment]
See https://github.com/jlowin/fastmcp/pull/42 for a fix

**Comment by jlowin** [comment]
I believe this was closed in #42, please reopen if not!

**Comment by jlowin** [comment]
(release should go out tonight)

**Comment by jlowin** [comment]
https://github.com/jlowin/fastmcp/releases/tag/v0.3.5
